=== Junior-Is-Great67/Leapster-2-Dragon-Kingdom-SRC/content/dragons/rsc/datasets/audio_dataset.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Data Wrangler Definition created by DataWrangler C, Version: 1.0.27
     Generated by Pentad Software Corporation for LeapFrog Enterprises, Inc. -->

<!ELEMENT audio_dataset (contentVersion, tables) >

<!ELEMENT contentVersion (#PCDATA)>

<!ELEMENT tables (table)* >

<!ELEMENT table (ids) >

<!ELEMENT ids (id)* >

<!ELEMENT id (idname, cells) >

<!ELEMENT idname (#PCDATA)>

<!ELEMENT cells (cell)* >

<!ELEMENT cell (entries) >

<!ELEMENT entries (entry)* >

<!ELEMENT entry (entrytype, entryhandle) >

<!ELEMENT entrytype (#PCDATA)>

<!ELEMENT entryhandle (#PCDATA)>

=== Junior-Is-Great67/Leapster-2-Dragon-Kingdom-SRC/content/dragons/rsc/datasets/audio_dataset0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE audio_dataset SYSTEM "audio_dataset.dtd">

<audio_dataset>
	<contentVersion>1.0</contentVersion>
	<tables>
		<table>
			<ids>
				<id>
					<idname>10</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_1_1</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>20</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_2_1</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>30</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_1_1</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>40</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_2_1</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
			</ids>
        </table>
		<table>
			<ids>
				<id>
					<idname>20</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_3_1</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>30</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_4_1</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>40</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_5_1</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>50</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_6_1</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>60</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_7_1</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>70</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_8_1</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>80</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_9_1</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>90</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_1_1</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>100</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_2_1</entryhandle>
								</entry>
								<entry>
									<entrytype>0</entrytype>
									<entryhandle>LPSR_BROM_BoingHi_6</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>110</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_3_1</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
            </ids>
		</table>
		<table>
			<ids>
				<id>
					<idname>10</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_3_1</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>20</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_4_1</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>30</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_5_1</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>40</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_6_1</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>50</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_7_1</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>60</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_8_1</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>70</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_9_1</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>80</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_1_1</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>90</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_2_1</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
				<id>
					<idname>100</idname>
					<cells>
						<cell>
							<entries>
								<entry>
									<entrytype>3</entrytype>
									<entryhandle>L_NA_3_1</entryhandle>
								</entry>
							</entries>
						</cell>
					</cells>
				</id>
            </ids>
		</table>
	</tables>
</audio_dataset>
