=== Junior-Is-Great67/Leapster-2-Dragon-Kingdom-SRC/content/dragons/rsc/datasets/dragonData.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Data Wrangler Definition created by DataWrangler ActionScript, Version: 1.0.27
     Generated by Pentad Software Corporation for LeapFrog Enterprises, Inc. -->

<!ELEMENT wordDataset (version, word_list) >

<!ELEMENT version (#PCDATA)>

<!ELEMENT word_list (wordStruct)* >

<!ELEMENT wordStruct (wordType, wordName, wordHi, wordID) >

<!ELEMENT wordType (#PCDATA)>

<!ELEMENT wordName (#PCDATA)>

<!ELEMENT wordHi (#PCDATA)>

<!ELEMENT wordID (#PCDATA)>

=== Junior-Is-Great67/Leapster-2-Dragon-Kingdom-SRC/content/dragons/rsc/datasets/dragonData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wordDataset SYSTEM "dragonData.dtd">
<wordDataset>
	<version>1</version>
	<word_list>
		<wordStruct>
			<wordType>easyS0</wordType>
			<wordName>t</wordName>
			<wordHi>t</wordHi>
			<wordID>10</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>n</wordName>
			<wordHi>n</wordHi>
			<wordID>20</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>r</wordName>
			<wordHi>r</wordHi>
			<wordID>30</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>i</wordName>
			<wordHi>i</wordHi>
			<wordID>40</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>m</wordName>
			<wordHi>m</wordHi>
			<wordID>50</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>d</wordName>
			<wordHi>d</wordHi>
			<wordID>60</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>s</wordName>
			<wordHi>s</wordHi>
			<wordID>70</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>l</wordName>
			<wordHi>l</wordHi>
			<wordID>80</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>e</wordName>
			<wordHi>e</wordHi>
			<wordID>90</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>o</wordName>
			<wordHi>o</wordHi>
			<wordID>100</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>b</wordName>
			<wordHi>b</wordHi>
			<wordID>110</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>f</wordName>
			<wordHi>f</wordHi>
			<wordID>120</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>v</wordName>
			<wordHi>v</wordHi>
			<wordID>130</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>t</wordName>
			<wordHi>t</wordHi>
			<wordID>140</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>n</wordName>
			<wordHi>n</wordHi>
			<wordID>150</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>r</wordName>
			<wordHi>r</wordHi>
			<wordID>160</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>i</wordName>
			<wordHi>i</wordHi>
			<wordID>170</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>m</wordName>
			<wordHi>m</wordHi>
			<wordID>180</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>d</wordName>
			<wordHi>d</wordHi>
			<wordID>190</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>s</wordName>
			<wordHi>s</wordHi>
			<wordID>200</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>l</wordName>
			<wordHi>l</wordHi>
			<wordID>210</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>j</wordName>
			<wordHi>j</wordHi>
			<wordID>220</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>easyS</wordType>
			<wordName>e</wordName>
			<wordHi>e</wordHi>
			<wordID>230</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS23</wordType>
			<wordName>k</wordName>
			<wordHi>k</wordHi>
			<wordID>10</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>p</wordName>
			<wordHi>p</wordHi>
			<wordID>20</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>g</wordName>
			<wordHi>g</wordHi>
			<wordID>30</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>h</wordName>
			<wordHi>h</wordHi>
			<wordID>40</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>w</wordName>
			<wordHi>w</wordHi>
			<wordID>50</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>u</wordName>
			<wordHi>u</wordHi>
			<wordID>60</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>j</wordName>
			<wordHi>j</wordHi>
			<wordID>70</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>x</wordName>
			<wordHi>x</wordHi>
			<wordID>80</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>q</wordName>
			<wordHi>q</wordHi>
			<wordID>90</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>z</wordName>
			<wordHi>z</wordHi>
			<wordID>100</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>y</wordName>
			<wordHi>y</wordHi>
			<wordID>110</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>o</wordName>
			<wordHi>o</wordHi>
			<wordID>120</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>u</wordName>
			<wordHi>u</wordHi>
			<wordID>130</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>i</wordName>
			<wordHi>i</wordHi>
			<wordID>140</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>a</wordName>
			<wordHi>a</wordHi>
			<wordID>150</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>hardS</wordType>
			<wordName>a</wordName>
			<wordHi>a</wordHi>
			<wordID>160</wordID>
		</wordStruct>		
		<wordStruct>
			<wordType>CVC40</wordType>
			<wordName>pan</wordName>
			<wordHi>p a n</wordHi>
			<wordID>10</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>cat</wordName>
			<wordHi>c a t</wordHi>
			<wordID>50</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>rat</wordName>
			<wordHi>r a t</wordHi>
			<wordID>90</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>fan</wordName>
			<wordHi>f a n</wordHi>
			<wordID>130</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>bad</wordName>
			<wordHi>b a d</wordHi>
			<wordID>170</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>sad</wordName>
			<wordHi>s a d</wordHi>
			<wordID>210</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>get</wordName>
			<wordHi>g e t</wordHi>
			<wordID>250</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>wet</wordName>
			<wordHi>w e t</wordHi>
			<wordID>300</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>ten</wordName>
			<wordHi>t e n</wordHi>
			<wordID>340</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>bed</wordName>
			<wordHi>b e d</wordHi>
			<wordID>380</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>hen</wordName>
			<wordHi>h e n</wordHi>
			<wordID>420</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>yes</wordName>
			<wordHi>y e s</wordHi>
			<wordID>460</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>bit</wordName>
			<wordHi>b i t</wordHi>
			<wordID>500</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>lid</wordName>
			<wordHi>l i d</wordHi>
			<wordID>540</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>wig</wordName>
			<wordHi>w i g</wordHi>
			<wordID>580</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>sit</wordName>
			<wordHi>s i t</wordHi>
			<wordID>620</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>mop</wordName>
			<wordHi>m o p</wordHi>
			<wordID>660</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>fox</wordName>
			<wordHi>f o x</wordHi>
			<wordID>700</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>dog</wordName>
			<wordHi>d o g</wordHi>
			<wordID>740</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>hog</wordName>
			<wordHi>h o g</wordHi>
			<wordID>780</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>job</wordName>
			<wordHi>j o b</wordHi>
			<wordID>820</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>mug</wordName>
			<wordHi>m u g</wordHi>
			<wordID>860</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>jug</wordName>
			<wordHi>j u g</wordHi>
			<wordID>900</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>bus</wordName>
			<wordHi>b u s</wordHi>
			<wordID>940</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>fun</wordName>
			<wordHi>f u n</wordHi>
			<wordID>980</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>run</wordName>
			<wordHi>r u n</wordHi>
			<wordID>1020</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVC</wordType>
			<wordName>cup</wordName>
			<wordHi>c u p</wordHi>
			<wordID>1060</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVCe67</wordType>
			<wordName>tape</wordName>
			<wordHi>t a p e</wordHi>
			<wordID>10</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVCe</wordType>
			<wordName>cave</wordName>
			<wordHi>c a v e</wordHi>
			<wordID>50</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVCe</wordType>
			<wordName>safe</wordName>
			<wordHi>s a f e</wordHi>
			<wordID>90</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVCe</wordType>
			<wordName>wake</wordName>
			<wordHi>w a k e</wordHi>
			<wordID>130</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVCe</wordType>
			<wordName>cape</wordName>
			<wordHi>c a p e</wordHi>
			<wordID>170</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVCe</wordType>
			<wordName>lake</wordName>
			<wordHi>l a k e</wordHi>
			<wordID>220</wordID>
		</wordStruct>
		<wordStruct>
			<wordType>CVCe</wordType>
			<wordName>date</wordName>
			<wordHi>d a t e</wordHi>
			<wordID>260</wordID>
		</wordStruct>
